-- La fuente de verdad del esquema son las migraciones versionadas en:
-- supabase/migrations/
--
-- Aplícalas con Supabase CLI (`supabase db push`) o copia su contenido,
-- en orden, en el SQL Editor para un bootstrap manual.
